#!/usr/bin/env python3
"""
Web Research Agent - A simple agent that searches the web and generates summaries.

This agent takes a research topic, performs web searches, and generates
a markdown report with key findings and sources.

Usage:
    python research_agent.py "Your research topic here"
"""

import sys
import json
import re
from datetime import datetime
from typing import List, Dict, Any

# Simulated web search function (replace with actual API in production)
def search_web(query: str, num_results: int = 5) -> List[Dict[str, str]]:
    """
    Simulate web search results.
    In production, replace with actual search API like Google Custom Search,
    Bing Search API, or SerpAPI.
    """
    # Simulated results for demonstration
    mock_results = {
        "python programming": [
            {"title": "Python Programming Language", "url": "https://python.org", "snippet": "Python is a high-level, interpreted programming language known for its simplicity."},
            {"title": "Learn Python - Full Course", "url": "https://example.com/python-course", "snippet": "Comprehensive Python tutorial covering basics to advanced topics."},
        ],
        "machine learning": [
            {"title": "Introduction to Machine Learning", "url": "https://example.com/ml-intro", "snippet": "Machine learning is a subset of AI that enables systems to learn from data."},
            {"title": "Machine Learning Algorithms", "url": "https://example.com/ml-algorithms", "snippet": "Common ML algorithms include linear regression, decision trees, and neural networks."},
        ],
        "default": [
            {"title": f"Search Result for: {query}", "url": "https://example.com/result1", "snippet": f"Information about {query} from various sources."},
            {"title": f"More on {query}", "url": "https://example.com/result2", "snippet": f"Additional details and insights about {query}."},
        ]
    }
    
    # Return relevant results or default
    for key in mock_results:
        if key in query.lower():
            return mock_results[key][:num_results]
    return mock_results["default"][:num_results]


def extract_keywords(text: str) -> List[str]:
    """Extract important keywords from the research topic."""
    # Simple keyword extraction (remove common words)
    common_words = {'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been',
                    'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will',
                    'would', 'could', 'should', 'may', 'might', 'must', 'shall',
                    'can', 'need', 'dare', 'ought', 'used', 'to', 'of', 'in',
                    'for', 'on', 'with', 'at', 'by', 'from', 'as', 'into',
                    'through', 'during', 'before', 'after', 'above', 'below',
                    'between', 'under', 'and', 'but', 'or', 'yet', 'so'}
    
    words = re.findall(r'\b[a-zA-Z]+\b', text.lower())
    keywords = [w for w in words if w not in common_words and len(w) > 3]
    return list(set(keywords))[:5]  # Return up to 5 unique keywords


def generate_summary(results: List[Dict[str, str]], topic: str) -> str:
    """Generate a summary from search results."""
    if not results:
        return "No results found for the given topic."
    
    summaries = []
    for i, result in enumerate(results, 1):
        summary = f"{i}. **{result['title']}**\n   - {result['snippet']}\n   - Source: {result['url']}"
        summaries.append(summary)
    
    return "\n".join(summaries)


def generate_report(topic: str, results: List[Dict[str, str]], keywords: List[str]) -> str:
    """Generate a markdown research report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    summary = generate_summary(results, topic)
    
    report = f"""# Research Report: {topic}

**Generated:** {timestamp}
**Keywords:** {', '.join(keywords)}

---

## Executive Summary

This report provides an overview of research findings for **"{topic}"**.
The following sections summarize key information gathered from web sources.

---

## Key Findings

{summary}

---

## Analysis

Based on the search results, here are the main insights:

1. **Primary Topic**: {topic}
2. **Number of Sources**: {len(results)}
3. **Key Themes**: {', '.join(keywords[:3]) if keywords else 'General research'}

---

## Recommendations

- Review the sources listed above for detailed information
- Consider exploring related topics: {', '.join(keywords[2:]) if len(keywords) > 2 else 'N/A'}
- Verify information from multiple sources before use

---

## Sources

"""
    
    for result in results:
        report += f"- [{result['title']}]({result['url']})\n"
    
    report += f"""
---

*Report generated by Web Research Agent*
"""
    return report


def save_report(report: str, filename: str = None) -> str:
    """Save the report to a file."""
    if filename is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_report_{timestamp}.md"
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(report)
    
    return filename


def main():
    """Main entry point for the research agent."""
    # Check command line arguments
    if len(sys.argv) < 2:
        print("Usage: python research_agent.py \"Your research topic here\"")
        print("\nExample:")
        print('  python research_agent.py "artificial intelligence trends"')
        sys.exit(1)
    
    # Get research topic from command line
    topic = sys.argv[1]
    
    print(f"🔍 Starting research on: {topic}")
    print("-" * 50)
    
    # Step 1: Extract keywords
    print("📋 Extracting keywords...")
    keywords = extract_keywords(topic)
    print(f"   Keywords found: {', '.join(keywords)}")
    
    # Step 2: Perform web search
    print("\n🌐 Searching web...")
    results = search_web(topic)
    print(f"   Found {len(results)} results")
    
    # Step 3: Generate report
    print("\n📝 Generating report...")
    report = generate_report(topic, results, keywords)
    
    # Step 4: Save report
    filename = save_report(report)
    print(f"   Report saved to: {filename}")
    
    # Step 5: Display summary
    print("\n" + "=" * 50)
    print("📊 RESEARCH SUMMARY")
    print("=" * 50)
    print(f"Topic: {topic}")
    print(f"Sources: {len(results)}")
    print(f"Keywords: {', '.join(keywords)}")
    print(f"Report: {filename}")
    print("\nPreview:")
    print("-" * 50)
    print(report[:500] + "..." if len(report) > 500 else report)
    
    return filename


if __name__ == "__main__":
    main()
